const obj ={
  id: 8269425541426,
  admin_graphql_api_id: 'gid://shopify/Order/8269425541426',
  app_id: 580111,
  browser_ip: '162.154.241.254',
  buyer_accepts_marketing: true,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: 'hWN3tAwtVqgttCFRKY9DleuQ',
  checkout_id: 39976693825842,
  checkout_token: '8bbc16af92e8c152f948b2b7b445456f',
  client_details: {
    accept_language: 'en-US',
    browser_height: null,
    browser_ip: '162.154.241.254',
    browser_width: null,
    session_hash: null,
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'
  },
  closed_at: null,
  confirmation_number: 'YZX4PT8V6',
  confirmed: true,
  contact_email: 'brandon@magnoliacremations.com',
  created_at: '2025-10-08T15:34:26-04:00',
  currency: 'USD',
  current_shipping_price_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  current_subtotal_price: '0.00',
  current_subtotal_price_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  current_total_additional_fees_set: null,
  current_total_discounts: '1388.00',
  current_total_discounts_set: {
    shop_money: { amount: '1388.00', currency_code: 'USD' },
    presentment_money: { amount: '1388.00', currency_code: 'USD' }
  },
  current_total_duties_set: null,
  current_total_price: '0.00',
  current_total_price_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  current_total_tax: '0.00',
  current_total_tax_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  customer_locale: 'en-US',
  device_id: null,
  discount_codes: [ { code: 'Test-Josh-Test', amount: '1388.00', type: 'percentage' } ],
  duties_included: false,
  email: 'brandon@magnoliacremations.com',
  estimated_taxes: false,
  financial_status: 'paid',
  fulfillment_status: null,
  landing_site: '/pages/services-packages-flow',
  landing_site_ref: null,
  location_id: null,
  merchant_business_entity_id: 'MTY3Njg3NTE0NDE4',
  merchant_of_record_app_id: null,
  name: '#3474',
  note: null,
  note_attributes: [
    {
      name: 'formData',
      value: '{"purchaser_first_name":"Brandon","purchaser_last_name":"Smith","purchaser_middle_name":"","purchaser_suffix":"","purchaser_email":"brandon@magnoliacremations.com","purchaser_phone":"502-435-3352","purchaser_street_address":"712 W 8th St","purchaser_city":"Flora","purchaser_state":"Illinois","purchaser_zip_code":"62839-1055","purchaser_relationship":"Spouse","contact_first_name":"Brandon","contact_last_name":"Smith","contact_middle_name":"","contact_suffix":"","contact_email":"brandon@magnoliacremations.com","contact_phone":"502-435-3352","contact_street_address":"712 W 8th St","contact_city":"Flora","contact_state":"Illinois","contact_zip_code":"62839-1055","contact_relationship":"Spouse","deceased_first_name":"Brandon","deceased_last_name":"Smith","deceased_middle_name":"","deceased_suffix":"","deceased_gender":"Male","deceased_date_birth":"Dec 17, 1991","deceased_date_death":"Oct 07, 2025","deceased_age":33,"deceased_street_address":"901 W 5th St","deceased_city":"Flora","deceased_state":"Illinois","deceased_zip_code":"62839-1156","deceased_social_security_number":"123-45-6789","pick_up_location_location_type":"Hospital","pick_up_location_facility_name":"Test Facility Name","pick_up_location_street_address":"900 Hospital Dr","pick_up_location_city":"Madisonville","pick_up_location_state":"Kentucky","pick_up_location_zip_code":"42431","place_of_passing_same_as_pickup":true,"place_of_passing_location_type":"Hospital","place_of_passing_facility_name":"Test Facility Name","place_of_passing_street_address":"900 Hospital Dr","place_of_passing_city":"Madisonville","place_of_passing_state":"Kentucky","place_of_passing_zip_code":"42431","private_family_viewing_price":0,"private_family_viewing_total":0,"witness_cremation_price":0,"witness_cremation_total":0,"death_certificates_price":20,"death_certificates_quantity":2,"death_certificates_title":"Death Certificates","death_certificates_total":40,"death_certificates_variant_id":45233081712946,"total_before_tax":1388,"shipping":0,"sales_tax":0,"total_order":1388,"transfer_fee_price":275,"transfer_fee_quantity":1,"transfer_fee_variant_id":49769855942962,"urn_details":"font:Lucida, Line 1:Test5678901234567890, Line 2:Test5678901234567890, Line 3:Test5678901234567890, Line 4:Test5678901234567890","urn_price":178,"urn_quantity":1,"urn_title":"Emerson Granite Memorial Urn","urn_variant_id":"49487949758770","urn_product_id":"gid://shopify/Product/9635649847602","urn_total":178,"service_package_package_name":"Essential Cremation Package","service_package_type":"Immediate Need","service_package_price":895,"service_package_variant_id":49214260904242,"license":"Indiana License #21100032","plan_ahead_person":"","preplanning_options_addTransferFee":"","preplanning_options_transferFee":"","preplanning_options_transferFeeCalculated":"","preplanning_options_addShipping":"","preplanning_options_stepCompleted":"","next_of_kin_options_spouse_first_name":"","next_of_kin_options_spouse_middle_name":"","next_of_kin_options_spouse_last_name":"","next_of_kin_options_spouse_suffix":"","next_of_kin_options_spouse_phone":"","next_of_kin_options_spouse_email":"","next_of_kin_options_spouse_street":"","next_of_kin_options_spouse_city":"","next_of_kin_options_spouse_state":"","next_of_kin_options_spouse_zip_code":"","next_of_kin_options_children_number":0,"next_of_kin_options_siblings_number":0,"next_of_kin_options_grand_children_number":0}'
    }
  ],
  number: 2474,
  order_number: 3474,
  order_status_url: 'https://magnoliacremations.com/67687514418/orders/79e74ee81fbd3448dd8ac4625043329f/authenticate?key=97ca6b23524c45882da4e144dd256a99',
  original_total_additional_fees_set: null,
  original_total_duties_set: null,
  payment_gateway_names: [],
  phone: null,
  po_number: null,
  presentment_currency: 'USD',
  processed_at: '2025-10-08T15:34:25-04:00',
  reference: null,
  referring_site: 'https://magnoliacremations.com/',
  source_identifier: null,
  source_name: 'web',
  source_url: null,
  subtotal_price: '0.00',
  subtotal_price_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  tags: '',
  tax_exempt: false,
  tax_lines: [],
  taxes_included: false,
  test: false,
  token: '79e74ee81fbd3448dd8ac4625043329f',
  total_cash_rounding_payment_adjustment_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  total_cash_rounding_refund_adjustment_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  total_discounts: '1388.00',
  total_discounts_set: {
    shop_money: { amount: '1388.00', currency_code: 'USD' },
    presentment_money: { amount: '1388.00', currency_code: 'USD' }
  },
  total_line_items_price: '1388.00',
  total_line_items_price_set: {
    shop_money: { amount: '1388.00', currency_code: 'USD' },
    presentment_money: { amount: '1388.00', currency_code: 'USD' }
  },
  total_outstanding: '0.00',
  total_price: '0.00',
  total_price_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  total_shipping_price_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  total_tax: '0.00',
  total_tax_set: {
    shop_money: { amount: '0.00', currency_code: 'USD' },
    presentment_money: { amount: '0.00', currency_code: 'USD' }
  },
  total_tip_received: '0.00',
  total_weight: 0,
  updated_at: '2025-10-08T15:34:27-04:00',
  user_id: null,
  billing_address: {
    first_name: 'Brandon',
    address1: '811 E Main St',
    phone: '+15024353352',
    city: 'Louisville',
    zip: '40206',
    province: 'Kentucky',
    country: 'United States',
    last_name: 'Smith',
    address2: null,
    company: null,
    latitude: 38.2548767,
    longitude: -85.736969,
    name: 'Brandon Smith',
    country_code: 'US',
    province_code: 'KY'
  },
  customer: {
    id: 9911262314802,
    created_at: '2025-09-05T15:09:35-04:00',
    updated_at: '2025-10-08T15:34:27-04:00',
    first_name: 'Brandon',
    last_name: 'Smith',
    state: 'disabled',
    note: '',
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    email: 'brandon@magnoliacremations.com',
    phone: '+15024353352',
    currency: 'USD',
    tax_exemptions: [],
    admin_graphql_api_id: 'gid://shopify/Customer/9911262314802',
    default_address: {
      id: 11506060329266,
      customer_id: 9911262314802,
      first_name: 'Brandon',
      last_name: 'Smith',
      company: null,
      address1: '811 E Main St',
      address2: null,
      city: 'Louisville',
      province: 'Kentucky',
      country: 'United States',
      zip: '40206',
      phone: '+15024353352',
      name: 'Brandon Smith',
      province_code: 'KY',
      country_code: 'US',
      country_name: 'United States',
      default: true
    }
  },
  discount_applications: [
    {
      target_type: 'line_item',
      type: 'discount_code',
      value: '100.0',
      value_type: 'percentage',
      allocation_method: 'across',
      target_selection: 'all',
      code: 'Test-Josh-Test'
    }
  ],
  fulfillments: [],
  line_items: [
    {
      id: 18563349184818,
      admin_graphql_api_id: 'gid://shopify/LineItem/18563349184818',
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Emerson Granite Memorial Urn - Yes',
      price: '178.00',
      price_set: [Object],
      product_exists: true,
      product_id: 9635649847602,
      properties: [Array],
      quantity: 1,
      requires_shipping: true,
      sales_line_item_group_id: null,
      sku: 'MC-2732L+E',
      taxable: true,
      title: 'Emerson Granite Memorial Urn',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 49487949758770,
      variant_inventory_management: null,
      variant_title: 'Yes',
      vendor: 'Magnolia Cremations',
      tax_lines: [],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 18563349217586,
      admin_graphql_api_id: 'gid://shopify/LineItem/18563349217586',
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Additional Mileage Fee - 151-160',
      price: '275.00',
      price_set: [Object],
      product_exists: true,
      product_id: 9769097789746,
      properties: [Array],
      quantity: 1,
      requires_shipping: false,
      sales_line_item_group_id: null,
      sku: '',
      taxable: false,
      title: 'Additional Mileage Fee',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 49769855942962,
      variant_inventory_management: null,
      variant_title: '151-160',
      vendor: 'Magnolia Cremations',
      tax_lines: [],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 18563349250354,
      admin_graphql_api_id: 'gid://shopify/LineItem/18563349250354',
      attributed_staffs: [],
      current_quantity: 2,
      fulfillable_quantity: 2,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Death Certificates',
      price: '20.00',
      price_set: [Object],
      product_exists: true,
      product_id: 8367453536562,
      properties: [Array],
      quantity: 2,
      requires_shipping: false,
      sales_line_item_group_id: null,
      sku: '',
      taxable: false,
      title: 'Death Certificates',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 45233081712946,
      variant_inventory_management: null,
      variant_title: null,
      vendor: 'Magnolia Cremations',
      tax_lines: [],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 18563349283122,
      admin_graphql_api_id: 'gid://shopify/LineItem/18563349283122',
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Essential Cremation Package - Immediate Need / Essential Cremation Package',
      price: '895.00',
      price_set: [Object],
      product_exists: true,
      product_id: 9589035106610,
      properties: [Array],
      quantity: 1,
      requires_shipping: true,
      sales_line_item_group_id: null,
      sku: '',
      taxable: false,
      title: 'Essential Cremation Package',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 49214260904242,
      variant_inventory_management: null,
      variant_title: 'Immediate Need / Essential Cremation Package',
      vendor: 'Magnolia Cremations',
      tax_lines: [],
      duties: [],
      discount_allocations: [Array]
    }
  ],
  payment_terms: null,
  refunds: [],
  shipping_address: null,
  shipping_lines: [
    {
      id: 6914269184306,
      carrier_identifier: null,
      code: 'Magnolia Cremations - Louisville, KY',
      current_discounted_price_set: [Object],
      discounted_price: '0.00',
      discounted_price_set: [Object],
      is_removed: false,
      phone: null,
      price: '0.00',
      price_set: [Object],
      requested_fulfillment_service_id: null,
      source: 'shopify',
      title: 'Magnolia Cremations - Louisville, KY',
      tax_lines: [],
      discount_allocations: []
    }
  ],
  returns: [],
  line_item_groups: []
}